per_listener_settings true

listener 8883

# Ścieżki do certyfikatów serwera 
certfile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/mqtt_broker.crt
keyfile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/mqtt_broker.key

# Ścieżka do CA 
cafile /home/rafal/Web_Speech_remote_control/sros2_ws/mqtt_certs/ca_root.crt

# Bezpieczeństwo
allow_anonymous false   # Zabroń wchodzenia bez certyfikatu
require_certificate true # Wymuś pokazanie certyfikatu przez klienta (mTLS)
use_identity_as_username true # Użyj nazwy z certyfikatu (CN) jako nazwy użytkownika
